config/urls.py
from django.contrib import admin
from django.urls import path, include

import reminder.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(
        reminder.urls, namespace='reminder'
    ))
]

reminder/urls.py
from django.urls import path
from . import views

"""Register our all url paths for our app"""

app_name = 'reminder'
urlpatterns = [
    path('', views.home, name='home'),
    path('appointments',
         views.AppointmentList.as_view(),
         name='AppointmentList'),
    path(r'create_appointments', views.create_appointment, name='create_appointment'),
]

reminder/models.py
from django.db import models
from .jobs import scheduler


class Appointment(models.Model):
    """Appointment schema"""
    title = models.CharField(max_length=100)
    content = models.TextField(default="")
    date = models.DateTimeField()
    tel = models.CharField(max_length=20)

    def __str__(self):
        return "{} {}".format(self.content, self.date)


# Start our scheduler
scheduler.start()

reminder/forms.py
from django import forms
from django.forms import ModelForm
from .models import Appointment


class AppointmentForm(ModelForm):
    """Appointment form which uses our Appointment model"""
    class Meta:
        model = Appointment
        fields = ['title', 'content', 'date', 'tel']
        widgets = {
            'date': forms.DateTimeInput(attrs={'id': 'input', 'style': "text-align: center"})
        }

reminder/views.py
from apscheduler.triggers.date import DateTrigger
from django.views.generic import ListView
from reminder.models import Appointment
from django.shortcuts import redirect
from django.shortcuts import render

from .forms import AppointmentForm
from .jobs import scheduler
from .sms import remind_appointment_schedule
from datetime import timedelta, datetime


class AppointmentList(ListView):
    """
    Structures our Appointment data in a list view
    """
    model = Appointment


def create_appointment(request):
    """
    View function to handle our create appointment form
    :param request: Contains our request object
    """
    # if this is a POST request we need to process the form data
    if request.method == 'POST':

        # request.POST is immutable, so we turn it to mutable so we can
        # edit the time date format from the form to a date time format to
        # match our model
        mutable = request.POST._mutable
        request.POST._mutable = True
        raw_date = request.POST['date'].split(' ')  # split our time and date values
        request.POST['date'] = ' '.join(raw_date[::-1])  # Reverse the date
        request.POST._mutable = mutable

        # create a form instance and populate it with data from the request:
        form = AppointmentForm(request.POST)

        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            form.save()

            appointment = Appointment.objects.last()  # retrieve last saved appointment object

            # Calculate 30 less than scheduled date
            reminder = datetime.strptime(form.data['date'], '%m/%d/%Y %H:%M') - timedelta(minutes=30)

            # Configure our scheduler for reminder
            trigger = DateTrigger(
                run_date=reminder
            )
            scheduler.add_job(remind_appointment_schedule, args=[appointment], trigger=trigger)
            # redirect to a new URL:
            return redirect('/appointments')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = AppointmentForm()

    return render(request, 'appointment_form.html', {'form': form})


def home(request):
    """View for our home page"""
    return render(request, 'home.html')

reminder/templates/reminder/appointment_form.html
{% extends 'index.html' %}
{% load material_form %}
{% block title %}Appointment Form{% endblock %}

{% block head %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.11/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.11/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">

    <style>
        .container {
          height: 200px;
          position: relative;
        }

        .center {
          margin: 0;
          position: absolute;
          top: 35%;
          left: 50%;
          -ms-transform: translate(-50%, -50%);
          transform: translate(-50%, -50%);
        }
    </style>
{% endblock %}

{% block content %}
    <div class="card center container">
        <div class="card-title" align="center">Schedule your Appointment here</div><br/>
        <form method="POST" class="card-panel">
            {% csrf_token %}
            {% form form=form %}{% endform %} <br/>
            <button type="submit" name="_submit" class="btn">Submit</button>

        </form>
    </div>
    <script>
        $('#input').datetimepicker({ footer: true, modal: true });
    </script>
{% endblock %}

reminder/templates/reminder/appointment_list.html
{% extends 'index.html' %}
{% load material_form %}
{% block title %}
    Appointment list
{% endblock %}

{% block content %}
    <h2>List of Scheduled Appointments</h2>
    <a href="{% url 'reminder:home' %}">
        <button class="btn">Home</button>
    </a>
    <ul>
        {% for appointment in object_list reversed %}
            <li class="card blue-grey darken-3">
                <div class="card-content white-text">
                    <span class="card-title">{{appointment.title}}</span>
                    <p>{{ appointment.content }}</p>
                    <p>Reminder Tel: {{ appointment.tel }} </p>
                    <p>Time: {{ appointment.date }} </p>
                </div>
            </li>
            {% empty %}
            <li>No appointment yet</li>
        {% endfor %}
    </ul>
{% endblock %}

reminder/templates/reminder/home.html
{% extends 'index.html' %}
{% block title %}
    Home
{% endblock %}

{% block head %}
    {# Load the tag library #}
    {% load bootstrap4 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
{% endblock %}
{% block content %}
    <div>
        <br/><br/><br/>
        <div class="jumbotron"><br/><br/><h1>Appointment Reminder</h1><br/><br/></div>
        <div>
            <a href="{% url 'reminder:create_appointment' %}"><button class="btn-large">Schedule Appointment</button></a>
            <a href="{% url 'reminder:AppointmentList' %}"><button class="btn-large">View Appointments</button></a>
        </div>

    </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Appointment Reminder{% endblock %}</title>
    {% include 'material/includes/material_css.html' %}
    {% include 'material/includes/material_js.html' %}

    {% block head %}{% endblock %}
</head>
<body>
    <div class="container center">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>